<a href="https://colab.research.google.com/github/PMattox/fs/blob/main/sftp_read.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install paramiko

Collecting paramiko
  Downloading paramiko-3.5.1-py3-none-any.whl.metadata (4.6 kB)
Collecting bcrypt>=3.2 (from paramiko)
  Downloading bcrypt-4.3.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: cryptography>=3.3 in /usr/local/lib/python3.11/dist-packages (from paramiko) (43.0.3)
Collecting pynacl>=1.5 (from paramiko)
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (8.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=3.3->paramiko) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=3.3->paramiko) (2.22)
Downloading paramiko-3.5.1-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.3/227.3 kB 6.7 MB/s eta 0:00:00
Downloading bcrypt-4.3.0-cp39-abi3-manylinux_2_34_x86_64.whl (284 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 12.3 MB/s eta 0:00:00
Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 17.7 MB/s eta 0:00:00
Installing collected packages: bcrypt, pynacl, paramiko
Successfully installed bcrypt-4.3.0 paramiko-3.5.1 pynacl-1.5.0

In [ ]:
# prompt: use getpass to save username and password into variables

# import getpass

# set up sftp access
# username and password are stored within Colab secrets
hostname = "mxre-e2e-files.parentlink.net"

In [ ]:
# prompt:  connect to an sftp and list the files

from google.colab import userdata # this enables the use of secrets
import paramiko

try:
    transport = paramiko.Transport((hostname, 22))
    # transport.connect(username=username, password=password)
        # this now leverages Colab notebook secrets
    transport.connect(username=userdata.get('mxre-e2e-sftp_user'), password=userdata.get('mxre-e2e-sftp_pw'))

    sftp = paramiko.SFTPClient.from_transport(transport)

    files = sftp.listdir()
    print("Files in the remote directory:")
    for file in files:
        print(file)

    sftp.close()
    transport.close()

except Exception as e:
    print(f"An error occurred: {e}")

Files in the remote directory:
.bash_logout
.bash_profile
.bashrc
.emacs
.virtualenvs
.bash_history
organization_anonimized.txt
SQL_out
SectionBig Spring ISDData_anonimized.txt
ScheduleBig Spring ISDData_anonimized.txt
CustomParentsBig Spring ISDData_anonimized.txt
CustomStaffBig Spring ISDData_anonimized.txt
CourseBig Spring ISDData_anonimized.txt
StudentBig Spring ISDData_anonimized.txt

In [ ]:
# load a file into a pandas df and display the head

import pandas as pd

try:
    transport = paramiko.Transport((hostname, 22))
    transport.connect(username=userdata.get('mxre-e2e-sftp_user'), password=userdata.get('mxre-e2e-sftp_pw'))

    sftp = paramiko.SFTPClient.from_transport(transport)
    filename = 'CustomParentsBig Spring ISDData_anonimized.txt'

    # Download the file
    remote_file_path = filename  # Replace with the actual file path on the server
    local_file_path = "/tmp/test.txt" # Specify the local path to save the file.
    sftp.get(remote_file_path, local_file_path)

    # Load the data into a pandas DataFrame
    try:
      df = pd.read_csv(local_file_path, delimiter='\t') # Assumes tab-separated file. Change delimiter if needed
    except pd.errors.ParserError:
        print("Error: Could not parse the file. Check the delimiter or file format.")

    sftp.close()
    transport.close()

except Exception as e:
    print(f"An error occurred: {e}")

print("Reading from the "+filename+" file on the SFTP")
df.head()

Reading from the CustomParentsBig Spring ISDData_anonimized.txt file on the SFTP

,organizationid,parentid,studentid,lastName,firstName,middleName,address1,address2,city,state,zip,primaryphoneNumber,homephoneNumber,workphoneNumber,otherphoneNumber,mobilephoneNumber,smsNumber,emailAddress,preferredLanguage1ID,pref
0,113,3deef4828c0760b56e41f59f2e4834915f3690dd,317485,Terry,Heidi,NaN,2311 Patrick Rapids,NaN,New Veronicafurt,UT,91865.0,(218)436-9095,NaN,4325287551,NaN,4325287551,(218)436-9095,fernandezjeffrey@example.com,98.0,C
1,111,89090e674f0c0839e8ba98baadc01e064c47442d,326736,Smith,Alec,NaN,1157 Keith Road,NaN,New Veronicafurt,UT,91865.0,NaN,NaN,NaN,NaN,3257333621,8146536866,lynnkaren@example.com,98.0,NaN
2,111,fe8898ce3fe3c8df5c9656a94ef53787357ef672,327271,Nelson,Joseph,NaN,5452 Herbert Valley,50,New Veronicafurt,UT,91865.0,NaN,NaN,NaN,NaN,4328163508,802-221-9308,susan22@example.com,98.0,NaN
3,113,6a3971230463a260eb0f441c25a6d71c7ecfc55b,319403,Wright,John,p,5052 Clark Pine,NaN,New Veronicafurt,UT,91865.0,9859384588,NaN,4326311734,NaN,4323062208,9859384588,kimberlywood@example.com,98.0,C
4,43,6a3971230463a260eb0f441c25a6d71c7ecfc55b,319690,Wright,John,NaN,5052 Clark Pine,NaN,New Veronicafurt,UT,91865.0,9859384588,NaN,NaN,4323062208,4323062208,9859384588,kimberlywood@example.com,98.0,C

In [ ]:
# prompt: find items in df where parentid like "2b26f0e205d55b2fb237f42e5c918a21ff767def"

# Convert the parentid column to string type to avoid potential errors
df['parentid'] = df['parentid'].astype(str)

# Use the .str.contains() method for partial string matching
matching_rows = df[df['parentid'].str.contains("2b26f0e205d55b2fb237f42e5c918a21ff767def", na=False)]

# Print the matching rows
matching_rows

,organizationid,parentid,studentid,lastName,firstName,middleName,address1,address2,city,state,zip,primaryphoneNumber,homephoneNumber,workphoneNumber,otherphoneNumber,mobilephoneNumber,smsNumber,emailAddress,preferredLanguage1ID,pref
4501,44,2b26f0e205d55b2fb237f42e5c918a21ff767def,316814,Bradley,Jennifer,NaN,1908 Jeremy Glens,NaN,New Veronicafurt,UT,91865.0,(456)716-2655,NaN,NaN,NaN,3185942482,(456)716-2655,raymond62@example.com,98.0,C
4502,110,2b26f0e205d55b2fb237f42e5c918a21ff767def,318685,Garrett,Jennifer,NaN,1908 Jeremy Glens,NaN,New Veronicafurt,UT,91865.0,(456)716-2655,NaN,NaN,NaN,3185942482,(456)716-2655,raymond62@example.com,98.0,C
4503,111,2b26f0e205d55b2fb237f42e5c918a21ff767def,325982,Bradley,Jennifer,NaN,1908 Jeremy Glens,NaN,New Veronicafurt,UT,91865.0,NaN,NaN,NaN,NaN,3185942482,(456)716-2655,raymond62@example.com,98.0,NaN

In [ ]:
# Use the .str.contains() method for partial string matching
matching_rows = df[df['parentid'].str.contains("3198622", na=False)]

# Print the matching rows
matching_rows

,organizationid,parentid,studentid,lastName,firstName,middleName,address1,address2,city,state,zip,primaryphoneNumber,homephoneNumber,workphoneNumber,otherphoneNumber,mobilephoneNumber,smsNumber,emailAddress,preferredLanguage1ID,pref
1722,110,3198622,319862,Bradley,Jennifer,NaN,8487 Emily Lock,NaN,New Veronicafurt,UT,91865.0,NaN,NaN,NaN,NaN,9567016078,(800)511-2925,NaN,98.0,NaN

In [ ]:
try:
    transport = paramiko.Transport((hostname, 22))
    transport.connect(username=userdata.get('mxre-e2e-sftp_user'), password=userdata.get('mxre-e2e-sftp_pw'))

    sftp = paramiko.SFTPClient.from_transport(transport)
    filename = 'StudentBig Spring ISDData_anonimized.txt'

    # Download the file
    remote_file_path = filename  # Replace with the actual file path on the server
    local_file_path = "/tmp/test.txt" # Specify the local path to save the file.
    sftp.get(remote_file_path, local_file_path)

    # Load the data into a pandas DataFrame
    try:
      df_student = pd.read_csv(local_file_path, delimiter='\t') # Assumes tab-separated file. Change delimiter if needed
    except pd.errors.ParserError:
        print("Error: Could not parse the file. Check the delimiter or file format.")

    sftp.close()
    transport.close()

except Exception as e:
    print(f"An error occurred: {e}")

print("Reading from the "+filename+" file on the SFTP")
df_student.head()

Reading from the StudentBig Spring ISDData_anonimized.txt file on the SFTP

,organizationid,studentid,lastName,firstName,middleName,gender,birthDate,gradeLevel,phoneNumber,address1,address2,city,zip,state,preferredLanguage1ID,homeLanguage,emailAddress,mobilephoneNumber,track
0,113,323106,Fischer,Kari,W,M,20160602,03,(703)752-6939,9779 Rebecca Wells,NaN,East Nataliestad,99477.0,WV,98,98,solomonnatalie@example.com,NaN,1
1,113,322957,Foster,Preston,z,M,20150313,03,397-613-6232,7462 Garcia Mall,NaN,East Nataliestad,99477.0,WV,01,01,vschneider@example.com,8439044272,1
2,113,319197,Salas,Monique,M,M,20160709,03,(766)473-0860,7975 Stuart Flats,NaN,East Nataliestad,99477.0,WV,98,98,cjenkins@example.com,NaN,1
3,113,319034,Martinez,David,h,F,20151130,03,3824025384,3007 Melissa Fall,NaN,East Nataliestad,99477.0,WV,98,98,valdezjanice@example.com,NaN,1
4,43,316494,Kelly,Michael,w,M,20110829,08,228-738-6729,6844 Sarah Square,NaN,East Nataliestad,99477.0,WV,NaN,98,david83@example.com,NaN,1

In [ ]:
# prompt: find records in df_student where studentid is in a list

# Assuming 'studentid' is the column name in df_student
student_ids_to_find = [316814, 318685, 325982]  # Replace with your list of student IDs

# Use the isin() method to find matching student IDs
matching_students = df_student[df_student['studentid'].isin(student_ids_to_find)]

# Print or process the matching records
matching_students

,organizationid,studentid,lastName,firstName,middleName,gender,birthDate,gradeLevel,phoneNumber,address1,address2,city,zip,state,preferredLanguage1ID,homeLanguage,emailAddress,mobilephoneNumber,track
1078,44,316814,Owens,Steven,U,M,20120911,06,393-716-8819,8644 David Points,NaN,East Nataliestad,99477.0,WV,NaN,98,mcunningham@example.com,NaN,1
2324,110,318685,Knight,Stephanie,Y,M,20160314,02,393-716-8819,8644 David Points,NaN,East Nataliestad,99477.0,WV,98,98,valerie25@example.com,NaN,1
3073,111,325982,Knight,Calvin,e,M,20190427,KG,4587403743,8644 David Points,NaN,East Nataliestad,99477.0,WV,98,98,reedjoshua@example.com,NaN,1



---

In [ ]:
# Use the .str.contains() method for partial string matching
matching_rows = df[df['parentid'].str.contains("8a773a4a809ac41cbe0fd5af063d9ff119ac80f7", na=False)]

# export the studentids into a list
selected_parents_students = matching_rows['studentid'].tolist()

# Print or process the matching rows
matching_rows

,organizationid,parentid,studentid,lastName,firstName,middleName,address1,address2,city,state,zip,primaryphoneNumber,homephoneNumber,workphoneNumber,otherphoneNumber,mobilephoneNumber,smsNumber,emailAddress,preferredLanguage1ID,pref
5474,110,8a773a4a809ac41cbe0fd5af063d9ff119ac80f7,318679,Smith,Kellie,NaN,1456 Lawrence Hills,NaN,New Veronicafurt,UT,91865.0,(490)349-4379,NaN,NaN,NaN,4322608587,(490)349-4379,cindy71@example.com,98.0,C

In [ ]:
# prompt: find records in df_student where studentid is in a list

# Assuming 'studentid' is the column name in df_student
student_ids_to_find = selected_parents_students  # Replace with your list of student IDs

# Use the isin() method to find matching student IDs
matching_students = df_student[df_student['studentid'].isin(student_ids_to_find)]

print("Children of the parent specified in the cell above")
# Print or process the matching records
matching_students

Children of the parent specified in the cell above

,organizationid,studentid,lastName,firstName,middleName,gender,birthDate,gradeLevel,phoneNumber,address1,address2,city,zip,state,preferredLanguage1ID,homeLanguage,emailAddress,mobilephoneNumber,track
2579,110,318679,Torres,Maurice,NaN,M,20151104,02,3822788674,5980 Bell Harbors,NaN,East Nataliestad,99477.0,WV,01,01,katherinehutchinson@example.com,NaN,1



---

In [ ]:
# prompt: find records in df_student where studentid is in a list

# Assuming 'studentid' is the column name in df_student
student_ids_to_find = [320617]  # Replace with your list of student IDs

# Use the isin() method to find matching student IDs
matching_students = df_student[df_student['studentid'].isin(student_ids_to_find)]

# Print or process the matching records
matching_students

,organizationid,studentid,lastName,firstName,middleName,gender,birthDate,gradeLevel,phoneNumber,address1,address2,city,zip,state,preferredLanguage1ID,homeLanguage,emailAddress,mobilephoneNumber,track
3286,110,320617,Massey,Samantha,k,F,20170624,02,3555498549,1266 Reed Inlet,NaN,East Nataliestad,99477.0,WV,01,01,bellyolanda@example.com,NaN,1